### ISSUE TITLE
Reliably use tools defined inside of Agents

### ISSUE THREAD

**Issue by fivegrant** [jataware/archytas#26]
When a `tool` is defined inside of an agent, it seems to be called incorrectly.

The specific case I ran into:
```
 Error while handling message llm_request in function llm_request
jupyter-1   | Traceback (most recent call last):
jupyter-1   |   File "/home/jupyter/.local/lib/python3.10/site-packages/archytas/react.py", line 204, in react_async
jupyter-1   |     tool_fn = self.tools[tool_name]
jupyter-1   | KeyError: 'search_installed_packages'
jupyter-1   | 
jupyter-1   | During handling of the above exception, another exception occurred:
jupyter-1   | 
jupyter-1   | Traceback (most recent call last):
jupyter-1   |   File "/home/jupyter/.local/lib/python3.10/site-packages/beaker_kernel/lib/utils.py", line 30, in wrapper
jupyter-1   |     result = await fn(self, message)
jupyter-1   |   File "/home/jupyter/.local/lib/python3.10/site-packages/beaker_kernel/kernel.py", line 440, in llm_request
jupyter-1   |     result = await self.context.agent.react_async(request, react_context={"message": message})
jupyter-1   |   File "/home/jupyter/.local/lib/python3.10/site-packages/archytas/react.py", line 206, in react_async
jupyter-1   |     action_str = await self.error(f'Unknown tool "{tool_name}"\nAvailable tools: {", ".join(self.tools.keys())}')
jupyter-1   |   File "/home/jupyter/.local/lib/python3.10/site-packages/archytas/react.py", line 302, in error
jupyter-1   |     raise FailedTaskError(f"Too many errors during task. Last error: {mesg}")
jupyter-1   | archytas.react.FailedTaskError: Too many errors during task. Last error: Unknown tool "search_installed_packages"
jupyter-1   | Available tools: Agent.ask_user, Agent.get_available_functions, Agent.get_functions_docstring, Agent.retrieve_documentation_for_module, Agent.search_installed_packages, Agent.submit_code
```

This agent class has a tool defined inside of it like this
```
@tool()
def search_installed_packages(self, code:str) -> str:
....
```
and it shows up in the list of available functions. However, the agent is unable to call the tool in the action loop

**Comment by fivegrant** [comment]
I suspect this is because the agent is failing to prepend `Agent.`
